"""Migrations: full round trip, and models == migrations (no drift)."""

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

from aeoi_db.config import database_url
from tests.integration.conftest import alembic_config

pytestmark = pytest.mark.integration


def test_downgrade_to_base_and_back(migrated_db: str) -> None:
    cfg = alembic_config(database_url(database=migrated_db).render_as_string(hide_password=False))
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")


def test_models_match_migrations(migrated_db: str) -> None:
    cfg = alembic_config(database_url(database=migrated_db).render_as_string(hide_password=False))
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"ORM models and migrations differ - create a migration:\n{exc}")


def test_round_trip_with_data_present(migrated_db: str) -> None:
    """A downgrade that only works on an empty database is not a real downgrade."""
    from aeoi_db.config import libpq_dsn
    from aeoi_synth.generate import Scale, generate
    from aeoi_synth.load import load

    load(generate(7, Scale.small()), libpq_dsn(database=migrated_db))
    cfg = alembic_config(database_url(database=migrated_db).render_as_string(hide_password=False))
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
