"""identity schema tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 19:00:32.967013+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.CheckConstraint("name ~ '^[a-z0-9-]+$'", name=op.f("ck_groups_name_format")),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_groups")),
        schema="identity",
    )
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "name ~ '^[a-z_]+:[a-z_]+(:[a-z_]+)?$'", name=op.f("ck_permissions_name_format")
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_permissions")),
        schema="identity",
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_roles")),
        schema="identity",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_users_external_subject")),
        schema="identity",
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True, schema="identity")
    op.create_table(
        "role_permissions",
        sa.Column("role_name", sa.String(length=40), nullable=False),
        sa.Column("permission_name", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_name"],
            ["identity.permissions.name"],
            name=op.f("fk_role_permissions_permission_name_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_name"],
            ["identity.roles.name"],
            name=op.f("fk_role_permissions_role_name_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_name", "permission_name", name=op.f("pk_role_permissions")),
        schema="identity",
    )
    op.create_index(
        "ix_role_permissions_permission_name",
        "role_permissions",
        ["permission_name"],
        unique=False,
        schema="identity",
    )
    op.create_table(
        "user_groups",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("group_name", sa.String(length=80), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["group_name"],
            ["identity.groups.name"],
            name=op.f("fk_user_groups_group_name_groups"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity.users.id"],
            name=op.f("fk_user_groups_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "group_name", name=op.f("pk_user_groups")),
        schema="identity",
    )
    op.create_index(
        "ix_user_groups_group_name", "user_groups", ["group_name"], unique=False, schema="identity"
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_name", sa.String(length=40), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_name"],
            ["identity.roles.name"],
            name=op.f("fk_user_roles_role_name_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity.users.id"],
            name=op.f("fk_user_roles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_name", name=op.f("pk_user_roles")),
        schema="identity",
    )
    op.create_index(
        "ix_user_roles_role_name", "user_roles", ["role_name"], unique=False, schema="identity"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_roles_role_name", table_name="user_roles", schema="identity")
    op.drop_table("user_roles", schema="identity")
    op.drop_index("ix_user_groups_group_name", table_name="user_groups", schema="identity")
    op.drop_table("user_groups", schema="identity")
    op.drop_index(
        "ix_role_permissions_permission_name", table_name="role_permissions", schema="identity"
    )
    op.drop_table("role_permissions", schema="identity")
    op.drop_index("ix_users_email", table_name="users", schema="identity")
    op.drop_table("users", schema="identity")
    op.drop_table("roles", schema="identity")
    op.drop_table("permissions", schema="identity")
    op.drop_table("groups", schema="identity")
    # ### end Alembic commands ###
