"""incident schema tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 19:00:42.366855+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate does not emit sequences: create it before the table that uses it.
    op.execute("CREATE SEQUENCE incident.incident_number_seq START WITH 10000")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "number",
            sa.BigInteger(),
            server_default=sa.text("nextval('incident.incident_number_seq')"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="OPEN", nullable=False),
        sa.Column(
            "affected_services",
            postgresql.ARRAY(sa.String(length=100)),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "severity IN ('SEV1', 'SEV2', 'SEV3', 'SEV4')", name=op.f("ck_incidents_severity_valid")
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'INVESTIGATING', 'AWAITING_REVIEW', 'MITIGATED', 'RESOLVED', 'CLOSED')",
            name=op.f("ck_incidents_status_valid"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('RESOLVED','CLOSED') OR resolved_at IS NOT NULL",
            name=op.f("ck_incidents_resolved_has_timestamp"),
        ),
        sa.CheckConstraint(
            "resolved_at IS NULL OR resolved_at >= detected_at",
            name=op.f("ck_incidents_resolved_after_detected"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
        sa.UniqueConstraint("number", name=op.f("uq_incidents_number")),
        schema="incident",
    )
    op.create_index(
        "ix_incidents_affected_services",
        "incidents",
        ["affected_services"],
        unique=False,
        schema="incident",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_incidents_status_severity_created_at",
        "incidents",
        ["status", "severity", sa.literal_column("created_at DESC")],
        unique=False,
        schema="incident",
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=40), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "headers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
        schema="incident",
    )
    op.create_index(
        "ix_outbox_unpublished",
        "outbox",
        ["created_at"],
        unique=False,
        schema="incident",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "processed_events",
        sa.Column("consumer", sa.String(length=80), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("consumer", "event_id", name=op.f("pk_processed_events")),
        schema="incident",
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("action_args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("args_sha256", sa.String(length=64), nullable=False),
        sa.Column("recommendation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_keys", postgresql.ARRAY(sa.String(length=80)), nullable=False),
        sa.Column("requested_by", sa.String(length=120), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decision", sa.String(length=12), nullable=True),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decider_role", sa.String(length=40), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "args_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_approvals_args_sha256_hex")
        ),
        sa.CheckConstraint(
            "consumed_at IS NULL OR decision = 'APPROVED'",
            name=op.f("ck_approvals_only_approved_consumed"),
        ),
        sa.CheckConstraint(
            "decision IS NULL OR decision IN ('APPROVED', 'REJECTED', 'MORE_INFO')",
            name=op.f("ck_approvals_decision_valid"),
        ),
        sa.CheckConstraint(
            "(decision IS NULL) = (decided_at IS NULL) AND (decision IS NULL) = (decided_by IS NULL)",
            name=op.f("ck_approvals_decision_fields_together"),
        ),
        sa.CheckConstraint(
            "decision IS NULL OR length(btrim(reason)) >= 3",
            name=op.f("ck_approvals_decision_needs_reason"),
        ),
        sa.CheckConstraint(
            "expires_at > requested_at", name=op.f("ck_approvals_expires_after_request")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incident.incidents.id"],
            name=op.f("fk_approvals_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        schema="incident",
    )
    op.create_index(
        "ix_approvals_incident_id_requested_at",
        "approvals",
        ["incident_id", "requested_at"],
        unique=False,
        schema="incident",
    )
    op.create_index(
        "uq_approvals_pending_action",
        "approvals",
        ["incident_id", "args_sha256"],
        unique=True,
        schema="incident",
        postgresql_where=sa.text("decision IS NULL"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("evidence_key", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_by", sa.String(length=64), nullable=False),
        sa.Column("tool_call_id", sa.UUID(), nullable=True),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_key LIKE kind || '-%%'", name=op.f("ck_evidence_key_matches_kind")
        ),
        sa.CheckConstraint(
            "kind IN ('LOG', 'METRIC', 'TRACE', 'DEPLOY', 'CONFIG', 'COMMIT', 'PR', 'DOC', 'RUNBOOK', 'INCIDENT', 'ALERT')",
            name=op.f("ck_evidence_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incident.incidents.id"],
            name=op.f("fk_evidence_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint(
            "incident_id", "evidence_key", name=op.f("uq_evidence_incident_id_evidence_key")
        ),
        schema="incident",
    )
    op.create_index(
        "ix_evidence_incident_id_kind",
        "evidence",
        ["incident_id", "kind"],
        unique=False,
        schema="incident",
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column("target_type", sa.String(length=12), nullable=False),
        sa.Column("target_id", sa.String(length=120), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('FINDING', 'REPORT', 'ANSWER', 'RETRIEVAL')",
            name=op.f("ck_feedback_target_type_valid"),
        ),
        sa.CheckConstraint("rating IN (-1, 1)", name=op.f("ck_feedback_rating_thumbs")),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incident.incidents.id"],
            name=op.f("fk_feedback_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        schema="incident",
    )
    op.create_index(
        "ix_feedback_incident_id", "feedback", ["incident_id"], unique=False, schema="incident"
    )
    op.create_index(
        "ix_feedback_target_type_target_id",
        "feedback",
        ["target_type", "target_id"],
        unique=False,
        schema="incident",
    )
    op.create_table(
        "hypotheses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="PROPOSED", nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("produced_by", sa.String(length=64), nullable=False),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f("ck_hypotheses_confidence_valid")
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED', 'CHALLENGED', 'VALIDATED', 'REJECTED', 'CONFIRMED')",
            name=op.f("ck_hypotheses_status_valid"),
        ),
        sa.CheckConstraint("rank >= 1", name=op.f("ck_hypotheses_rank_positive")),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incident.incidents.id"],
            name=op.f("fk_hypotheses_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["incident.hypotheses.id"],
            name=op.f("fk_hypotheses_superseded_by_hypotheses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hypotheses")),
        schema="incident",
    )
    op.create_index(
        "ix_hypotheses_incident_id_rank",
        "hypotheses",
        ["incident_id", "rank"],
        unique=False,
        schema="incident",
    )
    op.create_index(
        "ix_hypotheses_superseded_by",
        "hypotheses",
        ["superseded_by"],
        unique=False,
        schema="incident",
    )
    op.create_table(
        "incident_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("evidence_key", sa.String(length=80), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('DEPLOY', 'CONFIG', 'ALERT', 'LOG', 'METRIC', 'TRACE', 'HUMAN', 'AGENT', 'SYSTEM')",
            name=op.f("ck_incident_events_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incident.incidents.id"],
            name=op.f("fk_incident_events_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_events")),
        schema="incident",
    )
    op.create_index(
        "ix_incident_events_incident_id_occurred_at",
        "incident_events",
        ["incident_id", "occurred_at"],
        unique=False,
        schema="incident",
    )
    op.create_table(
        "hypothesis_evidence",
        sa.Column("hypothesis_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("stance", sa.String(length=12), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "stance IN ('SUPPORTS', 'CONTRADICTS')",
            name=op.f("ck_hypothesis_evidence_stance_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["incident.evidence.id"],
            name=op.f("fk_hypothesis_evidence_evidence_id_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["incident.hypotheses.id"],
            name=op.f("fk_hypothesis_evidence_hypothesis_id_hypotheses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "hypothesis_id", "evidence_id", name=op.f("pk_hypothesis_evidence")
        ),
        schema="incident",
    )
    op.create_index(
        "ix_hypothesis_evidence_evidence_id",
        "hypothesis_evidence",
        ["evidence_id"],
        unique=False,
        schema="incident",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_hypothesis_evidence_evidence_id", table_name="hypothesis_evidence", schema="incident"
    )
    op.drop_table("hypothesis_evidence", schema="incident")
    op.drop_index(
        "ix_incident_events_incident_id_occurred_at",
        table_name="incident_events",
        schema="incident",
    )
    op.drop_table("incident_events", schema="incident")
    op.drop_index("ix_hypotheses_superseded_by", table_name="hypotheses", schema="incident")
    op.drop_index("ix_hypotheses_incident_id_rank", table_name="hypotheses", schema="incident")
    op.drop_table("hypotheses", schema="incident")
    op.drop_index("ix_feedback_target_type_target_id", table_name="feedback", schema="incident")
    op.drop_index("ix_feedback_incident_id", table_name="feedback", schema="incident")
    op.drop_table("feedback", schema="incident")
    op.drop_index("ix_evidence_incident_id_kind", table_name="evidence", schema="incident")
    op.drop_table("evidence", schema="incident")
    op.drop_index(
        "uq_approvals_pending_action",
        table_name="approvals",
        schema="incident",
        postgresql_where=sa.text("decision IS NULL"),
    )
    op.drop_index(
        "ix_approvals_incident_id_requested_at", table_name="approvals", schema="incident"
    )
    op.drop_table("approvals", schema="incident")
    op.drop_table("processed_events", schema="incident")
    op.drop_index(
        "ix_outbox_unpublished",
        table_name="outbox",
        schema="incident",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox", schema="incident")
    op.drop_index(
        "ix_incidents_status_severity_created_at", table_name="incidents", schema="incident"
    )
    op.drop_index(
        "ix_incidents_affected_services",
        table_name="incidents",
        schema="incident",
        postgresql_using="gin",
    )
    op.drop_table("incidents", schema="incident")
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS incident.incident_number_seq")
