"""orchestrator schema tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 19:01:06.191484+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investigations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="RUNNING", nullable=False),
        sa.Column("requested_by", sa.String(length=120), nullable=False),
        sa.Column(
            "plan",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("budget_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column(
            "spent_usd", sa.Numeric(precision=10, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('RUNNING', 'AWAITING_REVIEW', 'COMPLETE', 'INCONCLUSIVE', 'FAILED', 'CANCELLED')",
            name=op.f("ck_investigations_status_valid"),
        ),
        sa.CheckConstraint(
            "budget_usd > 0 AND spent_usd >= 0", name=op.f("ck_investigations_budget_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigations")),
        schema="orchestrator",
    )
    op.create_index(
        "ix_investigations_incident_id_started_at",
        "investigations",
        ["incident_id", sa.literal_column("started_at DESC")],
        unique=False,
        schema="orchestrator",
    )
    op.create_index(
        "uq_investigations_one_running",
        "investigations",
        ["incident_id"],
        unique=True,
        schema="orchestrator",
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("investigation_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="PENDING", nullable=False),
        sa.Column("attempt", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column(
            "input",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT')",
            name=op.f("ck_tasks_status_valid"),
        ),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_tasks_attempt_positive")),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["orchestrator.investigations.id"],
            name=op.f("fk_tasks_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_tasks_idempotency_key")),
        schema="orchestrator",
    )
    op.create_index(
        "ix_tasks_investigation_id",
        "tasks",
        ["investigation_id"],
        unique=False,
        schema="orchestrator",
    )
    op.create_index(
        "ix_tasks_live_deadline",
        "tasks",
        ["deadline_at"],
        unique=False,
        schema="orchestrator",
        postgresql_where=sa.text("status IN ('PENDING','RUNNING')"),
    )
    op.create_table(
        "agent_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("agent_version", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("prompt_id", sa.String(length=80), nullable=True),
        sa.Column("prompt_version", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "cost_usd", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False
        ),
        sa.Column("retries", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "output",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT')",
            name=op.f("ck_agent_executions_status_valid"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_agent_executions_time_order"),
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0",
            name=op.f("ck_agent_executions_tokens_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["orchestrator.tasks.id"],
            name=op.f("fk_agent_executions_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_executions")),
        schema="orchestrator",
    )
    op.create_index(
        "ix_agent_executions_agent_name_started_at",
        "agent_executions",
        ["agent_name", sa.literal_column("started_at DESC")],
        unique=False,
        schema="orchestrator",
    )
    op.create_index(
        "ix_agent_executions_task_id",
        "agent_executions",
        ["task_id"],
        unique=False,
        schema="orchestrator",
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.SmallInteger(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('system', 'user', 'assistant', 'tool')", name=op.f("ck_messages_role_valid")
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["orchestrator.agent_executions.id"],
            name=op.f("fk_messages_execution_id_agent_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("execution_id", "seq", name=op.f("uq_messages_execution_id_seq")),
        schema="orchestrator",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages", schema="orchestrator")
    op.drop_index(
        "ix_agent_executions_task_id", table_name="agent_executions", schema="orchestrator"
    )
    op.drop_index(
        "ix_agent_executions_agent_name_started_at",
        table_name="agent_executions",
        schema="orchestrator",
    )
    op.drop_table("agent_executions", schema="orchestrator")
    op.drop_index(
        "ix_tasks_live_deadline",
        table_name="tasks",
        schema="orchestrator",
        postgresql_where=sa.text("status IN ('PENDING','RUNNING')"),
    )
    op.drop_index("ix_tasks_investigation_id", table_name="tasks", schema="orchestrator")
    op.drop_table("tasks", schema="orchestrator")
    op.drop_index(
        "uq_investigations_one_running",
        table_name="investigations",
        schema="orchestrator",
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.drop_index(
        "ix_investigations_incident_id_started_at",
        table_name="investigations",
        schema="orchestrator",
    )
    op.drop_table("investigations", schema="orchestrator")
    # ### end Alembic commands ###
