"""rag schema tables

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 19:01:08.026649+00:00
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("department", sa.String(length=80), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("allowed_groups", postgresql.ARRAY(sa.String(length=80)), nullable=False),
        sa.Column("sensitivity", sa.String(length=16), server_default="INTERNAL", nullable=False),
        sa.Column("quarantined", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "sensitivity IN ('INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')",
            name=op.f("ck_documents_sensitivity_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('markdown', 'pdf', 'txt', 'html', 'json', 'code', 'runbook', 'incident')",
            name=op.f("ck_documents_source_valid"),
        ),
        sa.CheckConstraint(
            "cardinality(allowed_groups) >= 1", name=op.f("ck_documents_has_allowed_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("source_uri", "version", name=op.f("uq_documents_source_uri_version")),
        schema="rag",
    )
    op.create_index(
        "ix_documents_allowed_groups",
        "documents",
        ["allowed_groups"],
        unique=False,
        schema="rag",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_documents_department_owner",
        "documents",
        ["department", "owner"],
        unique=False,
        schema="rag",
    )
    op.create_table(
        "historical_incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_key", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=False),
        sa.Column("root_cause_category", sa.String(length=60), nullable=False),
        sa.Column("remediation", sa.Text(), nullable=False),
        sa.Column("service_keys", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("allowed_groups", postgresql.ARRAY(sa.String(length=80)), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english'::regconfig, title || ' ' || summary || ' ' || root_cause)",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "incident_key ~ '^INC-[0-9]+$'", name=op.f("ck_historical_incidents_key_format")
        ),
        sa.CheckConstraint(
            "severity IN ('SEV1', 'SEV2', 'SEV3', 'SEV4')",
            name=op.f("ck_historical_incidents_severity_valid"),
        ),
        sa.CheckConstraint(
            "cardinality(allowed_groups) >= 1",
            name=op.f("ck_historical_incidents_has_allowed_groups"),
        ),
        sa.CheckConstraint(
            "embedding IS NULL OR embedding_model IS NOT NULL",
            name=op.f("ck_historical_incidents_embedding_has_model"),
        ),
        sa.CheckConstraint(
            "resolved_at >= occurred_at",
            name=op.f("ck_historical_incidents_resolved_after_occurred"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_incidents")),
        sa.UniqueConstraint("incident_key", name=op.f("uq_historical_incidents_incident_key")),
        schema="rag",
    )
    op.create_index(
        "ix_historical_incidents_embedding_hnsw",
        "historical_incidents",
        ["embedding"],
        unique=False,
        schema="rag",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_historical_incidents_occurred_at",
        "historical_incidents",
        [sa.literal_column("occurred_at DESC")],
        unique=False,
        schema="rag",
    )
    op.create_index(
        "ix_historical_incidents_service_keys",
        "historical_incidents",
        ["service_keys"],
        unique=False,
        schema="rag",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_historical_incidents_tsv",
        "historical_incidents",
        ["tsv"],
        unique=False,
        schema="rag",
        postgresql_using="gin",
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english'::regconfig, content)", persisted=True),
            nullable=False,
        ),
        sa.Column("allowed_groups", postgresql.ARRAY(sa.String(length=80)), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_document_chunks_chunk_index_non_negative")
        ),
        sa.CheckConstraint(
            "embedding IS NULL OR embedding_model IS NOT NULL",
            name=op.f("ck_document_chunks_embedding_has_model"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["rag.documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name=op.f("uq_document_chunks_document_id_chunk_index")
        ),
        schema="rag",
    )
    op.create_index(
        "ix_document_chunks_allowed_groups",
        "document_chunks",
        ["allowed_groups"],
        unique=False,
        schema="rag",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_document_chunks_embedding_hnsw",
        "document_chunks",
        ["embedding"],
        unique=False,
        schema="rag",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_document_chunks_tsv",
        "document_chunks",
        ["tsv"],
        unique=False,
        schema="rag",
        postgresql_using="gin",
    )
    op.create_table(
        "runbooks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("runbook_key", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("service_keys", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(steps) = 'array'", name=op.f("ck_runbooks_steps_is_array")
        ),
        sa.CheckConstraint(
            "runbook_key ~ '^RUNBOOK-[A-Z0-9]+-[0-9]{3}$'", name=op.f("ck_runbooks_key_format")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["rag.documents.id"],
            name=op.f("fk_runbooks_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runbooks")),
        sa.UniqueConstraint("runbook_key", "version", name=op.f("uq_runbooks_runbook_key_version")),
        schema="rag",
    )
    op.create_index(
        "ix_runbooks_document_id", "runbooks", ["document_id"], unique=False, schema="rag"
    )
    op.create_index(
        "ix_runbooks_service_keys",
        "runbooks",
        ["service_keys"],
        unique=False,
        schema="rag",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_runbooks_service_keys", table_name="runbooks", schema="rag", postgresql_using="gin"
    )
    op.drop_index("ix_runbooks_document_id", table_name="runbooks", schema="rag")
    op.drop_table("runbooks", schema="rag")
    op.drop_index(
        "ix_document_chunks_tsv", table_name="document_chunks", schema="rag", postgresql_using="gin"
    )
    op.drop_index(
        "ix_document_chunks_embedding_hnsw",
        table_name="document_chunks",
        schema="rag",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "ix_document_chunks_allowed_groups",
        table_name="document_chunks",
        schema="rag",
        postgresql_using="gin",
    )
    op.drop_table("document_chunks", schema="rag")
    op.drop_index(
        "ix_historical_incidents_tsv",
        table_name="historical_incidents",
        schema="rag",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_historical_incidents_service_keys",
        table_name="historical_incidents",
        schema="rag",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_historical_incidents_occurred_at", table_name="historical_incidents", schema="rag"
    )
    op.drop_index(
        "ix_historical_incidents_embedding_hnsw",
        table_name="historical_incidents",
        schema="rag",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("historical_incidents", schema="rag")
    op.drop_index("ix_documents_department_owner", table_name="documents", schema="rag")
    op.drop_index(
        "ix_documents_allowed_groups", table_name="documents", schema="rag", postgresql_using="gin"
    )
    op.drop_table("documents", schema="rag")
    # ### end Alembic commands ###
