"""devdata schema tables

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05 19:01:26.915062+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commits",
        sa.Column("sha", sa.String(length=40), nullable=False),
        sa.Column("repository", sa.String(length=120), nullable=False),
        sa.Column("service_key", sa.String(length=100), nullable=False),
        sa.Column("author", sa.String(length=120), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "files_changed",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("additions", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deletions", sa.Integer(), server_default="0", nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sha ~ '^[0-9a-f]{40}$'", name=op.f("ck_commits_sha_hex")),
        sa.PrimaryKeyConstraint("sha", name=op.f("pk_commits")),
        schema="devdata",
    )
    op.create_index(
        "ix_commits_repository_committed_at",
        "commits",
        ["repository", sa.literal_column("committed_at DESC")],
        unique=False,
        schema="devdata",
    )
    op.create_index(
        "ix_commits_service_key_committed_at",
        "commits",
        ["service_key", sa.literal_column("committed_at DESC")],
        unique=False,
        schema="devdata",
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deploy_key", sa.String(length=32), nullable=False),
        sa.Column("service_key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("environment", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("deployed_by", sa.String(length=120), nullable=False),
        sa.Column(
            "config_diff",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "deploy_key ~ '^DEPLOY-[0-9]+$'", name=op.f("ck_deployments_key_format")
        ),
        sa.CheckConstraint(
            "environment IN ('development', 'staging', 'production')",
            name=op.f("ck_deployments_environment_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('STARTED', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK')",
            name=op.f("ck_deployments_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployments")),
        sa.UniqueConstraint("deploy_key", name=op.f("uq_deployments_deploy_key")),
        schema="devdata",
    )
    op.create_index(
        "ix_deployments_service_key_environment_started_at",
        "deployments",
        ["service_key", "environment", sa.literal_column("started_at DESC")],
        unique=False,
        schema="devdata",
    )
    op.create_index(
        "ix_deployments_started_at",
        "deployments",
        ["started_at"],
        unique=False,
        schema="devdata",
        postgresql_using="brin",
    )
    op.create_table(
        "log_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_key", sa.String(length=100), nullable=False),
        sa.Column("level", sa.String(length=5), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL')",
            name=op.f("ck_log_events_level_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_log_events")),
        schema="devdata",
    )
    op.create_index(
        "ix_log_events_errors",
        "log_events",
        ["service_key", "ts", "error_code"],
        unique=False,
        schema="devdata",
        postgresql_where=sa.text("level IN ('ERROR','FATAL')"),
    )
    op.create_index(
        "ix_log_events_service_key_ts",
        "log_events",
        ["service_key", "ts"],
        unique=False,
        schema="devdata",
    )
    op.create_index(
        "ix_log_events_ts_brin",
        "log_events",
        ["ts"],
        unique=False,
        schema="devdata",
        postgresql_using="brin",
    )
    op.create_table(
        "metric_points",
        sa.Column("service_key", sa.String(length=100), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.PrimaryKeyConstraint("service_key", "metric", "ts", name=op.f("pk_metric_points")),
        schema="devdata",
    )
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repository", sa.String(length=120), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column("author", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("changed_files", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("merge_commit_sha", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(state = 'MERGED') = (merged_at IS NOT NULL)",
            name=op.f("ck_pull_requests_merged_has_time"),
        ),
        sa.CheckConstraint(
            "state IN ('OPEN', 'MERGED', 'CLOSED')", name=op.f("ck_pull_requests_state_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pull_requests")),
        sa.UniqueConstraint(
            "repository", "number", name=op.f("uq_pull_requests_repository_number")
        ),
        schema="devdata",
    )
    op.create_index(
        "ix_pull_requests_merge_commit_sha",
        "pull_requests",
        ["merge_commit_sha"],
        unique=False,
        schema="devdata",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pull_requests_merge_commit_sha", table_name="pull_requests", schema="devdata")
    op.drop_table("pull_requests", schema="devdata")
    op.drop_table("metric_points", schema="devdata")
    op.drop_index(
        "ix_log_events_ts_brin", table_name="log_events", schema="devdata", postgresql_using="brin"
    )
    op.drop_index("ix_log_events_service_key_ts", table_name="log_events", schema="devdata")
    op.drop_index(
        "ix_log_events_errors",
        table_name="log_events",
        schema="devdata",
        postgresql_where=sa.text("level IN ('ERROR','FATAL')"),
    )
    op.drop_table("log_events", schema="devdata")
    op.drop_index(
        "ix_deployments_started_at",
        table_name="deployments",
        schema="devdata",
        postgresql_using="brin",
    )
    op.drop_index(
        "ix_deployments_service_key_environment_started_at",
        table_name="deployments",
        schema="devdata",
    )
    op.drop_table("deployments", schema="devdata")
    op.drop_index("ix_commits_service_key_committed_at", table_name="commits", schema="devdata")
    op.drop_index("ix_commits_repository_committed_at", table_name="commits", schema="devdata")
    op.drop_table("commits", schema="devdata")
    # ### end Alembic commands ###
