"""tools schema tables

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 19:01:28.944604+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column("investigation_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("agent_name", sa.String(length=64), nullable=True),
        sa.Column("on_behalf_of", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("side_effect", sa.String(length=14), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "output_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("denial_reason", sa.Text(), nullable=True),
        sa.Column("approval_id", sa.UUID(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("attempt", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "side_effect <> 'CONSEQUENTIAL' OR status = 'DENIED' OR approval_id IS NOT NULL",
            name=op.f("ck_tool_calls_consequential_needs_approval"),
        ),
        sa.CheckConstraint(
            "side_effect IN ('READ', 'WRITE', 'CONSEQUENTIAL')",
            name=op.f("ck_tool_calls_side_effect_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'DENIED' OR denial_reason IS NOT NULL",
            name=op.f("ck_tool_calls_denial_has_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('OK', 'DENIED', 'ERROR', 'TIMEOUT')",
            name=op.f("ck_tool_calls_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
        schema="tools",
    )
    op.create_index(
        "ix_tool_calls_denied",
        "tool_calls",
        ["created_at"],
        unique=False,
        schema="tools",
        postgresql_where=sa.text("status = 'DENIED'"),
    )
    op.create_index(
        "ix_tool_calls_incident_id_created_at",
        "tool_calls",
        ["incident_id", "created_at"],
        unique=False,
        schema="tools",
    )
    op.create_index(
        "ix_tool_calls_tool_name_created_at",
        "tool_calls",
        ["tool_name", sa.literal_column("created_at DESC")],
        unique=False,
        schema="tools",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_calls_tool_name_created_at", table_name="tool_calls", schema="tools")
    op.drop_index("ix_tool_calls_incident_id_created_at", table_name="tool_calls", schema="tools")
    op.drop_index(
        "ix_tool_calls_denied",
        table_name="tool_calls",
        schema="tools",
        postgresql_where=sa.text("status = 'DENIED'"),
    )
    op.drop_table("tool_calls", schema="tools")
    # ### end Alembic commands ###
