"""llm schema tables

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-05 19:01:31.033668+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("operation", sa.String(length=24), nullable=False),
        sa.Column("prompt_id", sa.String(length=80), nullable=True),
        sa.Column("prompt_version", sa.Integer(), nullable=True),
        sa.Column("agent_name", sa.String(length=64), nullable=True),
        sa.Column("investigation_id", sa.UUID(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cached_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False
        ),
        sa.Column("status", sa.String(length=14), nullable=False),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operation IN ('generate', 'generate_structured', 'stream', 'embed')",
            name=op.f("ck_model_usage_operation_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('OK', 'ERROR', 'TIMEOUT', 'RATE_LIMITED', 'FALLBACK')",
            name=op.f("ck_model_usage_status_valid"),
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND cached_tokens >= 0",
            name=op.f("ck_model_usage_tokens_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_usage")),
        sa.UniqueConstraint("request_id", name=op.f("uq_model_usage_request_id")),
        schema="llm",
    )
    op.create_index(
        "ix_model_usage_created_at_brin",
        "model_usage",
        ["created_at"],
        unique=False,
        schema="llm",
        postgresql_using="brin",
    )
    op.create_index(
        "ix_model_usage_investigation_id",
        "model_usage",
        ["investigation_id"],
        unique=False,
        schema="llm",
    )
    op.create_index(
        "ix_model_usage_model_created_at",
        "model_usage",
        ["model", sa.literal_column("created_at DESC")],
        unique=False,
        schema="llm",
    )
    op.create_table(
        "prompt_versions",
        sa.Column("prompt_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_prompt_versions_sha_hex")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_prompt_versions_version_positive")),
        sa.PrimaryKeyConstraint("prompt_id", "version", name=op.f("pk_prompt_versions")),
        schema="llm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prompt_versions", schema="llm")
    op.drop_index("ix_model_usage_model_created_at", table_name="model_usage", schema="llm")
    op.drop_index("ix_model_usage_investigation_id", table_name="model_usage", schema="llm")
    op.drop_index(
        "ix_model_usage_created_at_brin",
        table_name="model_usage",
        schema="llm",
        postgresql_using="brin",
    )
    op.drop_table("model_usage", schema="llm")
    # ### end Alembic commands ###
