"""audit schema tables

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-05 19:01:32.951152+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("actor_role", sa.String(length=40), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=False),
        sa.Column("resource_id", sa.String(length=160), nullable=True),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.String(length=80), nullable=True),
        sa.Column("outcome", sa.String(length=8), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor ~ '^(user|service|agent):.+$'", name=op.f("ck_audit_events_actor_format")
        ),
        sa.CheckConstraint(
            "outcome IN ('SUCCESS', 'DENIED', 'FAILURE')",
            name=op.f("ck_audit_events_outcome_valid"),
        ),
        sa.PrimaryKeyConstraint("id", "occurred_at", name=op.f("pk_audit_events")),
        schema="audit",
        postgresql_partition_by="RANGE (occurred_at)",
    )
    op.create_index(
        "ix_audit_events_actor_occurred_at",
        "audit_events",
        ["actor", sa.literal_column("occurred_at DESC")],
        unique=False,
        schema="audit",
    )
    op.create_index(
        "ix_audit_events_correlation_id",
        "audit_events",
        ["correlation_id"],
        unique=False,
        schema="audit",
    )
    op.create_index(
        "ix_audit_events_incident_id_occurred_at",
        "audit_events",
        ["incident_id", "occurred_at"],
        unique=False,
        schema="audit",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_audit_events_incident_id_occurred_at", table_name="audit_events", schema="audit"
    )
    op.drop_index("ix_audit_events_correlation_id", table_name="audit_events", schema="audit")
    op.drop_index("ix_audit_events_actor_occurred_at", table_name="audit_events", schema="audit")
    op.drop_table("audit_events", schema="audit")
    # ### end Alembic commands ###
