"""Idempotency keys table; new permission incidents:create.

Why a new permission: 0012 gave incidents:write (change status, edit) only to incident
commanders, which meant an on-call ENGINEER could not even declare an incident. Declaring
and managing are different risks, so they get different permissions.
0012 is already merged, so it is not edited (migrations are immutable) - this adds to it.

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-05 19:37:01.948178+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("principal", sa.String(length=255), nullable=False),
        sa.Column("scope", sa.String(length=120), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.SmallInteger(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "request_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_idempotency_keys_request_sha256_hex")
        ),
        sa.CheckConstraint(
            "length(key) BETWEEN 8 AND 128", name=op.f("ck_idempotency_keys_key_length")
        ),
        sa.PrimaryKeyConstraint("principal", "scope", "key", name=op.f("pk_idempotency_keys")),
        schema="incident",
    )
    op.create_index(
        "ix_idempotency_keys_expires_at",
        "idempotency_keys",
        ["expires_at"],
        unique=False,
        schema="incident",
    )
    op.create_index(
        "ix_incidents_created_at_id",
        "incidents",
        [sa.text("created_at DESC"), sa.text("id DESC")],
        unique=False,
        schema="incident",
    )
    op.execute(
        "COMMENT ON INDEX incident.ix_incidents_created_at_id IS "
        "'serves: unfiltered incident list, keyset pagination (created_at, id) newest first'"
    )
    op.execute(
        "COMMENT ON INDEX incident.ix_idempotency_keys_expires_at IS "
        "'serves: cleanup job deleting expired idempotency keys'"
    )
    op.execute(
        "INSERT INTO identity.permissions (name, description) VALUES "
        "('incidents:create', 'Declare a new incident')"
    )
    op.execute(
        "INSERT INTO identity.role_permissions (role_name, permission_name) VALUES "
        "('ENGINEER', 'incidents:create'), ('SRE', 'incidents:create'), "
        "('INCIDENT_COMMANDER', 'incidents:create')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DELETE FROM identity.role_permissions WHERE permission_name = 'incidents:create'")
    op.execute("DELETE FROM identity.permissions WHERE name = 'incidents:create'")
    op.drop_index("ix_incidents_created_at_id", table_name="incidents", schema="incident")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_idempotency_keys_expires_at", table_name="idempotency_keys", schema="incident"
    )
    op.drop_table("idempotency_keys", schema="incident")
    # ### end Alembic commands ###
