"""tools.audit_outbox: audit events for tool calls, delivered by a relay (ADR-017).

Written in the same transaction as tools.tool_calls, so every tool call - allowed or denied -
has an audit event that survives an audit-service outage. Additive: safe on a live system.

Also tightens svc_tool_gateway (least privilege, ADR-017):
- tools.tool_calls becomes append-only (INSERT/SELECT): the gateway must not be able to
  rewrite or erase the record of what an agent did.
- tools.audit_outbox: no DELETE/TRUNCATE (the relay only marks rows delivered). Retention of
  delivered rows is a job run by the owner role, not by the service.
- devdata.* becomes read-only: in Phase 7 every tool is READ. These tables simulate external
  systems; the only writer is the seed (migration owner). Phase 16 grants the deployer the
  one UPDATE it needs, on purpose and visibly.

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-06 19:18:20.516109+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_outbox")),
        schema="tools",
    )
    op.create_index(
        "ix_audit_outbox_undelivered",
        "audit_outbox",
        ["created_at"],
        unique=False,
        schema="tools",
        postgresql_where=sa.text("delivered_at IS NULL"),
    )
    # ### end Alembic commands ###
    op.execute(
        "COMMENT ON INDEX tools.ix_audit_outbox_undelivered IS "
        "'serves: relay polling \"next undelivered events in order\" - partial = only the backlog'"
    )
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON tools.tool_calls FROM svc_tool_gateway")
    op.execute("REVOKE DELETE, TRUNCATE ON tools.audit_outbox FROM svc_tool_gateway")
    op.execute(
        "REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA devdata "
        "FROM svc_tool_gateway"
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES FOR ROLE CURRENT_USER IN SCHEMA devdata "
        "REVOKE INSERT, UPDATE, DELETE ON TABLES FROM svc_tool_gateway"
    )


def downgrade() -> None:
    op.execute(
        "ALTER DEFAULT PRIVILEGES FOR ROLE CURRENT_USER IN SCHEMA devdata "
        "GRANT INSERT, UPDATE, DELETE ON TABLES TO svc_tool_gateway"
    )
    op.execute("GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA devdata TO svc_tool_gateway")
    op.execute("GRANT DELETE ON tools.audit_outbox TO svc_tool_gateway")
    op.execute("GRANT UPDATE, DELETE ON tools.tool_calls TO svc_tool_gateway")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_audit_outbox_undelivered",
        table_name="audit_outbox",
        schema="tools",
        postgresql_where=sa.text("delivered_at IS NULL"),
    )
    op.drop_table("audit_outbox", schema="tools")
    # ### end Alembic commands ###
